@startuml  package proyectoAncianos {     package dao {         class AsistenteDAO         class AsistentePersonaDAO         class Conexion         class PadecimientoDAO         class PadecimientoPersonaDAO         class PersonaDAO         class RegistroLlamadaDAO     }      package dto {         class Asistente         class AsistentePersona         class Padecimiento         class PadecimientoPersona         class Persona         class RegistroLlamada     }      package negocio {         class GestorAncianos     }      package ui {         class AncianoGUI     }      class Main }  @enduml